FROM rocker/shiny

RUN apt-get update -y
# r-cran-xml is needed for R XML package
RUN apt-get install -y r-cran-xml

# installing necessary CRAN packages:
RUN R -e "install.packages( c('data.table', 'stringr'), repos='https://cloud.r-project.org/' )"

# installing necessary Bioconductor Packages:
RUN R -e 'source("https://bioconductor.org/biocLite.R"); biocLite(c("GenomicRanges", "rtracklayer"), suppressUpdates=F, suppressAutoUpdate=T, ask=F)'

RUN rm -rf /srv/shiny-server && mkdir /srv/shiny-server && mkdir /srv/shiny-server/LEG && chown shiny.shiny -R /srv/shiny-server && rm -rf /etc/shiny-server/shiny-server.conf
COPY app.R /srv/shiny-server/LEG/
COPY ./shiny-server.conf /etc/shiny-server/

RUN mkdir /srv/shiny-server/LEG/data/ && mkdir /srv/shiny-server/LEG/www/

COPY ./data/top10000_combined_mm9.Rdata ./data/top10000_combined.Rdata ./data/top10000_SOR_mm9.Rdata ./data/top10000_SOR.Rdata ./data/predictions_SOR.bdg.gz.tbi ./data/predictions_SOR.bdg.gz ./data/predictions_Ridge.bdg.gz.tbi ./data/predictions_Ridge.bdg.gz ./data/mm9ToMm10.over.chain ./data/impute_ranks_combined.Rdata ./data/impute_ranks_SOR.Rdata ./data/hg38_predictions_SOR.sorted.bed.gz.tbi ./data/hg38_predictions_SOR.sorted.bed.gz ./data/hg38_predictions_Ridge.sorted.bed.gz.tbi ./data/hg38_predictions_Ridge.sorted.bed.gz ./data/hg19ToHg38.over.chain ./data/160216_velements.Rdata ./data/160216_promoters_ensemblTSS_v83.Rdata /srv/shiny-server/LEG/data/
COPY  ./www/Slide1.PNG ./www/Slide2.PNG ./www/Slide3.PNG ./www/iframeResizer.contentWindow.min.js /srv/shiny-server/LEG/www/
COPY ./title_page.Rmd /srv/shiny-server/LEG/

EXPOSE 3838

# now run 'docker build -t rmonti/leg -f dockerfile_LEG .'
# then: 'docker run -m 4g --rm --publish 3838:3838 --name leg rmonti/leg'
# then visit localhost:3838 in your browser!
# If all is OK: 'docker push rmonti/leg'
